name: "Publish Python Package"

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        
jobs:
  PublishToCodeArtifact:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_RELEASE_PUBLISH_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true

      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@7e46c3fa1c1f217e26a73712796b1f78938b534b # v1.0.18
        with:
          project-name: ${{ github.event.repository.name }}-release-Publish
          hide-cloudwatch-logs: true
          source-version-override: refs/tags/${{inputs.tag}}