name: "E2E Tests"

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  E2ETests:
    if: (github.repository == 'aws-deadline/${{inputs.repository}}')
    name: E2E Tests
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{inputs.branch}}
      
      - name: Configure AWS credentials for release
        if: ${{inputs.branch == 'release'}}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_RELEASE_E2E_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true
          role-duration-seconds: 7200
       
      - name: Configure AWS credentials for mainline
        if: ${{inputs.branch == 'mainline'}}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_MAINLINE_E2E_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true
          role-duration-seconds: 7200
        
      - name: Run E2E Tests
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{inputs.repository}}-${{inputs.branch}}-${{inputs.os}}-e2e
          hide-cloudwatch-logs: true
          env-vars-for-codebuild: |
              TEST_TYPE,
              OPERATING_SYSTEM
        env:
          TEST_TYPE: WHEEL
          OPERATING_SYSTEM: ${{inputs.os}}