name: "Integration Tests"

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        if: ${{inputs.branch == 'mainline' || inputs.branch == 'release'}}
        with:
          ref: ${{inputs.branch}}
      
      - name: Configure AWS credentials for release
        if: ${{inputs.branch == 'release'}}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_RELEASE_INTEG_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true
       
      - name: Configure AWS credentials for mainline
        if: ${{inputs.branch == 'mainline'}}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_MAINLINE_INTEG_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true
        
      - name: Run Integration Tests
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{inputs.repository}}-${{inputs.branch}}-IntegTest
          hide-cloudwatch-logs: true
          env-vars-for-codebuild: |
              TEST_TYPE
        env:
          TEST_TYPE: WHEEL